export const TOPIC_NOUN = [
  'bananas',
  'slaves',
  'humans',
  'elves',
  'orcs',
  'neko',
  'tigerkin',
  'fairies',
  'angels',
  'dragonkin',
  'lizardkin',
  'foreigners',
  'quests',
  'adventuring',
  'swords',
  'axes',
  'bows',
  'dragons',
  'cooking',
  'mead',
  'game',
  'poetry',
  'sports',
  'exercise',
  'muscle',
  'sex',
  'anal sex',
  'oral sex',
  'vaginal sex',
  'pony slave',
  'pet slave',
  'music',
  'painting',
  'health',
  'history',
  'mathematics',
  'animals',
  'plants',
  'dick',
  'balls',
  'vagina',
  'anus',
  'breasts',
  'relationships',
  'religion',
  'politics',
  'love life',
  'crime',
  'slaving career',
  'knights',
  'peasants',
  'milk',
  'trading',
  'magic',
  'northern vale',
  'southern seas',
  'western forests',
  'eastern deserts',
  'deep',
  'bimbos',
  'mindbroken slaves',
  'fleshshaping',
  'corruption',
  'purification',
  'duties',
  'money',
  'fame',
  'fashion',
  'armor',
  'bondage',
  'submissive slaves',
  'dominant slavers',
  'technology',
  'romance',
  'love',
  'pets',
  'education',
  'mercenaries',
  'pirates',
  'whores',
  'soldiers',
  'raiders',
  'demons',
  'healers',
  'healing',
  'crafting',
  'potions',
  'trauma',
  'equipments',
  'work',
  'combat',
  'survival',
  'stealth',
  'slaving',
  'knowledge',
  'family',
  'nipples',
  'wings',
  'tail',
  'healsluts',
  'friendship',
  'rivalry',
  'mistakes',
  'triumphs',
  'tomorrow',
  'yesterday',
  'next month',
  'last month',
  'next week',
  'last week',
  'hypnotism',
  'domestic slaves',
  'sissies',
  'exhibitionism',
  'edging',
  'roleplaying',
  'sex addiction',
  'ghosts',
  'nature',
  'sleeping',
  'puns',
  'home',
  'hygiene',
  'science',
  'tentacles',
  'favors',
  'eldritch abominations',
  'Neko Port City',
  'harems',
  'low wages',
  'wet dreams',
  "dinner",
  "indigestion",
  "the Mist",
  "the cold",
  "the heat",
  "old flames",
  "sex protection",
  "fungus",
  "feet",
  "barbells",
  "chafing",
  "cats",
  "dogs",
  "philosophy",
  "tea",
  "rumors",
  "big butts",
  "flat butts",
  "cake",
  "birthdays",
  "injuries",
  "dancing",
  "prisoners",
  "networking",
  "one-night stands",
  "orc tusks",
  "elf ears",
  "peach fuzz",
  "other worlds",
  "dildos",
  "fresh fruits",
  "the afterlife",
  "sunrise",
  "sunset",
  "liquor",
  'tail sex',
  'missionary position',
  'brothels',
  'fire magic',
  'water magic',
  'earth magic',
  'wind magic',
  'dark magic',
  'light magic',
  'stale cheese',
  'tentacle monster',
  'insomnia',
  'defiant slaves',
  'mercenaries',
  'wishing wells',
  'undead',
  'blindfolds',
  'cream pie',
  'virginity',
  'monsters',
  'vegetables',
  'corpses',
]

export const BANTER_TOPIC = [
  'you',
  'your race',
  'your gender',
  'your personality',
  'your skills',
  'your career',
  'the company',
  'recent events',
  'slaves',
  'new slaves',
  'their past life',
  'humans',
  'elves',
  'the Kingdom of Tor',
  'the City of Lucgate',
  'orcs',
  'neko',
  'tigerkin',
  'fairies',
  'angels',
  'dragonkin',
  'lizardkin',
  'foreigners',
  'quests',
  'recent quests',
  'past quests',
  'adventuring',
  'swords',
  'dragons',
  'culture',
  'cooking',
  'hobbies',
  'literature',
  'art',
  'entertainment',
  'game',
  'poetry',
  'sports',
  'exercise',
  'muscle',
  'sex',
  'anal sex',
  'oral sex',
  'vaginal sex',
  'pony slave',
  'pet slave',
  'music',
  'painting',
  'health',
  'history',
  'mathematics',
  'animals',
  'plants',
  'dick',
  'balls',
  'vagina',
  'anus',
  'breasts',
  'relationships',
  'religion',
  'politics',
  'love life',
  'crime',
  'slaving career',
  'knights',
  'peasants',
  'milk',
  'trading',
  'magic',
  'northern vale',
  'southern seas',
  'western forests',
  'eastern deserts',
  'bimbos',
  'mindbroken slaves',
  'fleshshaping',
  'corruption',
  'purification',
  'duties',
  'your leadership',
  'their friends',
  'their rivals',
  'the future',
  'the past',
  'the world',
  'their dreams',
  'money',
  'fame',
  'travel',
  'the weather',
  'food',
  'fashion',
  'armor',
  'bondage',
  'naked',
  'submissive slaves',
  'dominant slavers',
  'technology',
  'romance',
  'love',
  'pets',
  'education',
  'mercenaries',
  'pirates',
  'whores',
  'soldiers',
  'raiders',
  'demons',
  'healers',
  'healing',
  'crafting',
  'potions',
  'trauma',
  'equipments',
  'their background',
  'their gender',
  'their race',
  'their personality',
  'work',
  'combat',
  'survival',
  'stealth',
  'slaving',
  'knowledge',
  'social life',
  'sex life',
  'family',
  'nipples',
  'wings',
  'tail',
  'healsluts',
  'friendship',
  'rivalry',
  'mistakes',
  'triumphs',
  'the fort',
  'tomorrow',
  'yesterday',
  'next month',
  'last month',
  'next week',
  'last week',
  'hypnotism',
  'breaking slaves',
  'domestic slaves',
  'sissies',
  'exhibitionism',
  'edging',
  'roleplaying',
  'sex addiction',
  'ghosts',
  'nature',
  'sleeping',
  'puns',
  'home',
  'hygiene',
  'science',
  'tentacles',
  'favors',
  'eldritch abominations',
  'Neko Port City',
  'harems',
  'low wages',
  'wet dreams',
  "dinner",
  "indigestion",
  "the Mist",
  "the cold",
  "the heat",
  "old flames",
  "sex protection",
  "a bad rash",
  "fungus",
  "feet",
  "working out",
  "saving up",
  "getting new clothes",
  "chafing",
  "the thing",
  "getting stains out of clothing",
  "favorite songs",
  "regular cats",
  "weapon maintenance",
  "holey underwear",
  "wearing a mask while raiding",
  "the ethics of slaving",
  "philosophy",
  "tea",
  "rumors",
  "that smell",
  "tall people",
  "short people",
  "big butts",
  "flat butts",
  "cake",
  "birthdays",
  "injuries",
  "scars",
  "childhood friends",
  "perfect handwriting",
  "awful handwriting",
  "new slavers",
  "the meaning of your name",
  "our glorious leader",
  "dancing",
  "prisoners",
  "favorite slaves",
  "networking",
  "one-night stands",
  "the night sky",
  "orc tusks",
  "elf ears",
  "peach fuzz",
  "other worlds",
  "dildos",
  "fresh fruits",
  "the afterlife",
  "sunrise",
  "sunset",
  "camp nightlife",
  "elven hand-woven rugs",
  "Southern Lands dragonspice",
  "orc liquor",
  "werewolf soaps",
  "neko milk-mead",
  "Northern fur coats",
  "Lucgate pickpockets",
  "Eastern crystal tooth-knives",
  "Kingdom of Tor eggplant dishes",
  "seaman-sucking sea serpents",
  "Mist culinary",
  'tail sex',
  'missionary position',
  'brothels',
  'fire magic',
  'water magic',
  'earth magic',
  'wind magic',
  'dark magic',
  'light magic',
  'stale cheese',
  'tentacle monster',
  'bad hangover',
  'insomnia',
  'defiant slaves',
  'your titles',
  "your company's reputation",
  'the latest quest',
  'mercenaries',
  'wishing wells',
  'undead',
  'blindfolds',
  'cream pie',
  'virginity',
  'monsters',
  'vegetables',
  'corpses',
  'bananas',
]
