export const BANTER_VERB_SLAVER_FRIEND = [
  {
    verbs: [
      `talked with b|rep`,
      `chatted with b|rep`,
      `gossiped with b|rep`,
      `discussed with b|rep`,
      `conversed with b|rep`,
      `practiced with b|rep`,
      `joked with b|rep`,
      `flirted with b|rep`,
      `schemed with b|rep`,
      `planned with b|rep`,
      `humored b|rep`,
      `hanged out with b|rep, talking`,
      `flirted with b|rep`,
      `spent time with b|rep, talking`,
      `befriended b|rep while discussing`,
      `advised b|rep`,
      `asked for b|reps advice`,
      `helped b|rep`,
      `relaxed with b|rep while talking`,
      `rested with b|rep while talking`,
      `supported b|rep while discussing`,
      `messed around with b|rep while talking`,
      `confessed to b|rep`,
      `gambled with b|rep while joking`,
      `agreed with what b|rep thinks`,
      `supported what b|rep thinks`,
      `gives consent on what b|rep thinks`,
      `learned b|reps opinions`,
      `exchanged opinions with b|rep`,
      `exchanged thoughts with b|rep`,
      `victimized something together with b|rep while talking`,
      `theorized with b|rep`,
      `enjoyed talking with b|rep`,
      `did maintenance work with b|rep while talking`,
      `ate together with b|rep while chatting`,
      `drinked together with b|rep while talking`,
      `bathed together with b|rep while talking`,
      `greeted b|rep`,
      `told a joke to b|rep`,
      `understood what b|reps thoughts are`,
      `shared a secret with b|rep`,
      `shared a bed with b|rep while talking`,
      `saluted b|rep`,
      `hugged b|rep`,
      `shared a story to b|rep`,
      `shared a book to b|rep`,
      `asked b|rep`,
      `praised b|rep`,
      `acknowledged b|reps knowledge`,
      `asked for b|reps knowledge`,
      `talked about b|reps past`,
      `calmed b|rep`,
      `cheered b|rep up`,
      `complimented b|rep`,
      `apologized to b|rep`,
      `commended b|rep`,
      `expressed admiration towards b|rep`,
      `flattered b|rep`,
      `commiserated with b|rep`,
      `tricked b|rep into thinking`,
      `lost to b|rep at skipping rocks, while idly speaking`,
      `pointed out shapes in the clouds to b|rep, while musing`,
      `idly honed a knife while talking to b|rep`,
      `sat around camp with b|rep, oiling up a blade while discussing`,
      `polished some armor to a mirror shine, while b|rep rambled on`,
      `sewed up torn clothes with b|rep while chatting`,
      `aired out some wet laundry with b|rep while talking`,
      `chopped wood with b|rep while discussing`,
      `scrubbed b|reps back with a washcloth while talking`,
      `dug into b|reps meal, stopping in between bites to discuss`,
      `choked down some stale biscuits together with b|rep, chatting`,
      `ate half a wheel of Northern Vale cheese, because of a bet with b|rep`,
      `gnawed on leathery werewolf-made jerky, pausing occasionally to talk to b|rep`,
      `shared a couple elven fruits with b|rep while conversing`,
      `shared a meal of neko paella with b|rep and chatted`,
      `watched as b|rep finished off an Eastern flatbread with rice, while talking`,
      `scarfed down an orc-style kebab that b|rep made, while b|rep blabbered`,
      `sucked down a bowl of "dragon whisker" noodles together with b|rep, speaking`,
      `wondered if the raw fish b|rep caught was good enough to make sushi, while chatting`,
      `handed b|rep some of the weak local table beer, while chatting`,
      `downed a shot of werewolf potato-liquor while rambling to b|rep`,
      `cracked open a cask of Northern Vale stout with b|rep to talk`,
      `downed a bottle of neko mead together with b|rep, while discussing`,
      `cried into a glass of elven wine, confessing to b|rep`,
      `stared at a fruit-laden cocktail concoction from Lucgate, while conversing with b|rep`,
      `sipped a cup of Eastern coffee while talking with b|rep`,
      `mixed a spoonful of neko honey into b|reps coffee, while gossiping`,
      `brewed a pot of tea while chatting with b|rep`,
      `swilled around the tea dregs while speaking to b|rep`,
      `marveled at the draconic firewater that b|rep brought, who spoke`,
      `flaunted a|their a|body at b|rep to show a|their point`,
      `asked b|rep if b|they would have a time to discuss`,
      `won b|rep over with a|their superior knowledge on`,
    ],
  },
]

export const BANTER_VERB_SLAVER_RIVAL = [
  {
    verbs: [
      `intimidated b|rep about`,
      `punched b|rep because of`,
      `slapped b|rep because of`,
      `pranked b|rep because of`,
      `insulted b|rep about`,
      `offended b|rep about`,
      `slighted b|rep about`,
      `snubbed b|rep because of`,
      `slandered b|rep about`,
      `kicked b|rep because of`,
      `hit b|rep because of`,
      `fought with b|rep because of`,
      `disagreed with b|rep about`,
      `debated with b|rep about`,
      `contradicted b|rep about`,
      `clashed with b|rep about`,
      `challenged b|reps authority about`,
      `challenged b|reps skills about`,
      `challenged b|reps opinions about`,
      `belittled b|reps authority about`,
      `belittled b|reps skills about`,
      `belittled b|reps opinions about`,
      `annoyed b|rep about`,
      `argued with b|rep about`,
      `disputed b|rep about`,
      `altercated with b|rep about`,
      `confronted b|rep about`,
      `trashed b|rep about`,
      `provoked b|rep about`,
      `took issue with b|rep about`,
      `opposed b|rep about`,
      `defied b|rep about`,
      `discredited b|rep about`,
      `trash-talked b|rep about`,
      `humiliated b|rep about`,
      `mortified b|rep about`,
      `shunned b|rep because of`,
      `spurned b|rep about`,
      `disparaged b|rep about`,
      `scorned b|rep about`,
      `defamed b|rep about`,
      `bitched to b|rep about`,
      `complained to b|rep about`,
      `protested to b|rep about`,
      `criticized b|rep about`,
      `denounced b|rep about`,
      `condemned b|rep about`,
      `attacked b|rep about`,
      `bad-mouthed b|rep about`,
      `roasted b|rep about`,
      `displeased b|rep about`,
      `irritated b|rep about`,
      `angered b|rep about`,
      `survived some of b|reps home cooking by conversing about`,
      `denied b|rep any of the Northern whale-butter because of a disagreement over`,
      `stole b|reps Wasteland rock candy, while pretending to talk about`,
      `spilled hot orc curry on b|rep during a heated discussion regarding`,
      `chucked a bowl of soup at b|rep, after an argument about`,
      `got wasted on sake and started a brawl with b|rep over`,
      `almost vomited when hearing b|reps opinions about`,
      `let out a sigh after discussing`,
      `disturbed by b|reps opinion on`,
      `disturbed b|rep by describing in too much details about`,
      `annoyed b|rep by repeatedly asking b|them about`,
      `questioned b|reps opinion on`,
      `had a disagreement with b|rep about`,
      `slapped b|reps ass in response to b|their opinion on`,
      `berated b|rep about`,
      `played a prank on b|rep themed after`,
      `silently judged b|reps thoughts on`,
    ],
  },
]


export const BANTER_VERB_SLAVER_LOVER = [
  {
    /* generic */
    verbs: [
      `kissed b|rep`,
      `caressed b|rep`,
      `hugged b|rep`,
      `made love with b|rep`,
      `slept with b|rep`,
      `smooched b|rep`,
      `praised b|rep`,
      `had a small chat with b|rep`,
      `had sex with b|rep`,
      `had a small chat with b|rep`,

      `embraced b|rep`,
      `danced with b|rep`,
      `stripped for b|rep`,
      `put on a show for b|rep`,
      `dressed sexily for b|rep`,
      `invited b|rep for some sexy time`,
      `gave b|rep a surprise sex`,
      `climaxed together with b|rep`,
      `talked dirtily with b|rep`,
      `played with b|reps nipples`,

      `enjoyed b|reps body`,
      `rested together with b|rep`,
      `serviced b|rep`,
      `victimize a slave together with b|rep`,
      `aroused b|rep`,
      `stared at b|reps eyes`,
      `gazed at b|reps face`,
      `exchanged kisses with b|rep`,
      `tongue-kissed with b|rep`,
      `licked b|reps body`,

      `smelled b|reps armpits`,
      `touched body with b|rep`,
      `locked in a kiss with b|rep`,
      `touched b|reps face`,
      `sang for b|rep`,
      `ate privately with b|rep`,
      `put a sexy attire for b|rep`,
      `made b|rep horny`,
      `caressed b|reps body`,
      `shaked ass for b|rep`,
    ],
  },
  {
    initiator: ["per_submissive"],
    verbs: [
      `submitted to b|rep`,
      `offered body to b|rep`,
      `offered genitals to b|rep`,
      `role-played as a slave for b|rep`,
      `role-played as a fucktoy for b|rep`,
      `worshipped b|rep`,
    ],
  },
  {
    target: ["muscle_strong"],
    verbs: [
      `touched b|reps muscles`,
      `groped b|reps muscles`,
      `traced b|reps muscles`,
    ],
  },
  {
    target: ["muscle_thin"],
    verbs: [
      `appreciated b|reps b|body`,
      `traced b|reps waist`,
    ],
  },
  {
    target: ["per_submissive"],
    verbs: [
      `dominated b|rep`,
      `objectified b|rep`,
      `toyed with b|reps b|body`,
      `manhandled b|rep`,
      `played master-slave with b|rep`,
    ],
  },
  {
    initiator: ["per_dominant"],
    target: ["per_submissive"],
    verbs: [
      `abused b|rep`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    target: ["vagina_tight"],
    verbs: [
      `fucked b|rep in the pussy`,
      `pussy-fucked b|rep`,
    ],
  },
  {
    target: ["vagina_tight"],
    verbs: [
      `ate b|reps pussy`,
      `fingered b|reps pussy`,
      `played with b|reps clit`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    verbs: [
      `anally fucked b|rep`,
      `came on top of b|rep`,
      `offered dick to b|rep`,
    ],
  },
  {
    initiator: ["vagina_tight"],
    verbs: [
      `pussy-sit on b|rep`,
      `offered vagina to b|rep`,
    ],
  },
  {
    target: ["dick_tiny"],
    verbs: [
      `gave b|rep a blow job`,
      `gave b|rep a hand job`,
      `groped b|reps b|dick`,
      `gave b|rep$ a surprise orgasm`,
    ],
  },
  {
    target: ["breast_tiny"],
    verbs: [
      `groped b|reps b|breasts`,
      `played with b|reps b|breasts`,
    ],
  },
  {
    initiator: ["breast_tiny"],
    target: ["breast_tiny"],
    verbs: [
      `collided breasts with b|rep`,
    ],
  },
]


export const BANTER_VERB_SLAVE_CARE = [
  {
    verbs: [
      `cared for b|rep`,
      `appeased b|rep`,
      `fostered b|rep`,
      `nurtured b|rep`,
      `stimulated b|rep`,
      `healed b|rep`,
      `took care of b|rep`,
      `looked after b|rep`,
      `watched over b|rep`,
      `aided b|rep`,
      `enriched b|rep`,
      `helped b|rep`,
      `strengthened b|rep`,
      `helped b|rep recover`,
      `talked with b|rep`,
      `supported b|reps slave duties`,
      `gently used b|rep`,
      `gently fuck b|rep`,
      `gently have sex with b|rep`,
      `tended b|rep`,
      `cheered b|rep`,
      `guarded b|rep`,
      `catered to b|rep`,
      `shared a story with b|rep`,
      `left b|rep alone`,
      `gave b|rep some food`,
      `fed b|rep`,
      `groomed b|rep`,
      `petted b|rep`,
      `hugged b|rep`,
      `stroked b|rep`,
      `caressed b|rep`,
      `fondled b|rep`,
      `patted b|rep`,
      `cuddled b|rep`,
      `pampered b|rep`,
      `indulged b|rep`,
      `embraced b|rep`,
      `reassured b|rep`,
      `comforted b|rep`,
      `encouraged b|rep`,
      `soothed b|rep`,
      `calmed b|rep`,
      `pacified b|rep`,
      `lulled b|rep`,
      `taught b|rep`,
      `allayed b|reps fears`,
      `allowed b|rep to rest`,
      `sang a lullaby for b|rep`,
      `gave b|rep some rest`,
    ],
  },
]


export const BANTER_VERB_SLAVE_ABUSE = [
  {
    /* generic */
    verbs: [
      `abused b|rep`,
      `punished b|rep`,
      `mistreated b|rep`,
      `fucked b|rep`,
      `manhandled b|rep`,
      `ill-treated b|rep`,
      `misused b|rep`,
      `molested b|rep`,
      `hit b|rep`,
      `beat b|rep`,
      `bullied b|rep`,
      `tortured b|rep`,
      `roughed b|rep up`,
      `disgraced b|rep`,
      `dehumanized b|rep`,
      `kicked b|rep`,
      `maltreated b|rep`,
      `used b|rep`,
      `violated b|rep`,
      `ravaged b|rep`,
      `harmed b|rep`,
      `harassed b|rep`,
      `tormented b|rep`,
      `forced b|rep to lick a|their armpits`,
      `forced b|rep to lick a|their a|genital`,
      `humiliated b|rep`,
      `shamed b|rep`,
      `edged b|rep`,
      `whipped b|rep`,
      `flogged b|rep`,
      `pinched b|reps nipples`,
      `twisted b|reps nipples`,
      `pulled b|reps nipples`,
      `degraded b|rep`,
      `made b|rep lick a|their a|anus`,
      `made b|rep eat a|their a|ass`,
      `spanked b|rep`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    verbs: [
      `face-fucked b|rep`,
      `sprayed b|reps face with cum`,
      `anally fucked b|rep`,
      `made b|rep choke on a|their a|dick`,
      `came in b|reps b|anus`,
      `made b|rep suck a|their a|dick`,
      `made b|rep deepthroat a|their a|dick`,
      `dickslapped b|rep`,
      `made b|rep kiss a|their a|dick`,
      `made b|rep lick a|their a|dick`,
    ],
  },
  {
    target: ["dick_tiny"],
    verbs: [
      `tortured b|reps b|dick`,
      `stepped on b|reps b|dick`,
      `made b|rep eat b|their own cum`,
      `edged b|rep`,
      `played with b|reps b|dick`,
      `clamped b|reps b|dick`,
      `spanked b|reps b|dick`,
      `shocked b|reps b|dick`,
      `slapped b|reps b|dick`,
      `pinched b|reps b|dick`,
    ],
  },
  {
    target: ["breast_tiny"],
    verbs: [
      `tortured b|reps b|breasts`,
      `stepped on b|reps b|breasts`,
      `made b|rep drink b|their own milk from b|their b|breasts`,
      `fondled b|reps b|breasts`,
      `played with b|reps b|breasts`,
      `clamped b|reps b|breasts`,
      `spanked b|reps b|breasts`,
      `shocked b|reps b|breasts`,
      `slapped b|reps b|breasts`,
      `pinched b|reps b|breasts`,
    ],
  },
  {
    target: ["balls_tiny"],
    verbs: [
      `tortured b|reps b|balls`,
      `stepped on b|reps b|balls`,
      `made b|rep eat b|their own cum`,
      `fondled b|reps b|balls`,
      `played with b|reps b|balls`,
      `clamped b|reps b|balls`,
      `spanked b|reps b|balls`,
      `shocked b|reps b|balls`,
      `slapped b|reps b|balls`,
      `pinched b|reps b|balls`,
    ],
  },
  {
    target: ["vagina_tight"],
    initiator: ["dick_tiny"],
    verbs: [
      `vaginally fucked b|rep`,
      `filled b|reps b|vagina with cum`,
      `played with b|reps b|vagina`,
      `inserted dildos into b|reps b|vagina`,
      `abused b|reps b|vagina`,
    ],
  },
]

/* special case: slave with no training */
export const BANTER_TRAINING_NONE = [
  `a|spit defiance with a|their every word`,
  `a|look at their captors deviantly`,
  `a|crave a|their freedom`,
  `a|angrily looks at your slavers`,
  `a|continue to mock your slavers`,

  `a|continue defying most of commands given to a|them`,
  `still a|believe a|they a|is a free person`,
  `still a|believe in being rescued one day`,
  `a|is still holding on to foolish concepts such as freedom`,
  `defiantly a|swear given any opportunity`,

  `a|try to defy a|their training`,
  `a|remain untamed`,
  `a|continue to cling to hope`,
  `defiantly a|disobey the commands given to a|them`,
  `intentionally a|go against a|their given commands`,

  `a|break a|their slave rules`,
  `still a|abhor the concept of slavery`,
  `passionately a|hate your company`,
  `a|is angered by a|their predicament`,
  `a|continue to swear to end your company`,
]

/* special case: mindbroken slaves */
export const BANTER_TRAINING_MINDBREAK = [
  `a|have a blank look`,
  `always a|remain unfocused`,
  `a|remain in a constant daze`,
  `always a|sport the same expression`,
  `a|is unresponsive to stimulus`,

  `a|drool continuously`,
  `a|is unable to process any information`,
  `a|do not understand a|their situation`,
  `a|is completely mindbroken`,
  `a|have completely lost a|their higher thought process`,

  `a|is nothing more than a hollowed-out fucktoy`,
  `a|is always staring into the distance`,
  `a|maintain an unfocused gaze`,
  `a|is unable to process any commands`,
  `a|is unable to understand anything that is happening around a|them`,

  `a|have already lost a|their capability of thinking`,
  `a|possess pupils that never move around`,
  `a|give your slavers a blank stare`,
  `a|do not respond to your slavers' abuse`,
  `a|have neither free nor enforced will`,
]

/* basic, advanced, master training */
export const BANTER_TRAINING_VERB = [
  [
    `reluctantly a|ask for`, `uncomfortably a|ask for`, `a|is made to beg for`,
    `unwillingly a|ask for`, `a|is forced to ask for`,
  ],
  [
    `a|beg for`, `a|crave`, `a|have been trained to beg for`,
    `a|seek`, `a|ask permission for`,
  ],
  [
    `cannot help but beg for`,
    `intensely a|crave`,
    `instinctively a|seek`,
    `a|is willing to do anything for`,
    `constantly a|degrade a|themself in hope for`,
    `a|have undergone extensive training to always crave`,
  ],
]

/* training texts */
export const BANTER_TRAINING_OBJECT = {
  training_obedience_basic: [
    `a|their next order`,
    `a|their next instructions`,
    `the next command from a|their`,
    `a|their owner's instructions`,
    `permission from a|their owner`,
    `order from a|their owner`,
    `a|their owner's orders`,
    `a|their owner's orders`,
    `your orders`,
    `your instructions`,
  ],
  training_oral_basic: [
    `dick to suck`,
    `cum to swallow`,
    `dick to deepthroat`,
    `dick to lick`,
    `dick to worship with a|their mouth`,
    `a|their owner's dick to be shoved into a|their mouth`,
    `a|their owner's dick to spray cum all over a|their mouth`,
    `a|their owner's cum to lick off the floor`,
    `a dildo to suck while waiting for a|their next serving of dick`,
    `your genitals`,
  ],
  training_anal_basic: [
    `dick to be shoved into a|their ass`,
    `dick to fill a|their ass with cum`,
    `dicks to fill a|their ass`,
    `dicks to penetrate a|their needy ass`,
    `dick to pleasure with a|their ass`,
    `a|their owner's dick to be shoved into a|their ass`,
    `a|their owner's dick to fill a|their ass full with cum`,
    `several dicks to fill a|their ass full`,
    `a dildo to plug over a|their ass while waiting for a|their next serving of dick`,
    `your genitals`,
  ],
  training_vagina_basic: [
    `dick to be shoved into a|their vagina`,
    `dick to fill a|their vagina with cum`,
    `dicks to fill a|their vagina`,
    `dicks to penetrate a|their needy vagina`,
    `dick to pleasure with a|their vagina`,
    `a|their owner's dick to be shoved into a|their vagina`,
    `a|their owner's dick to fill a|their vagina full with cum`,
    `several dicks to fill a|their vagina full`,
    `a dildo to plug over a|their vagina while waiting for a|their next serving of dick`,
    `your genitals`,
  ],
  training_sissy_basic: [
    `owner to pleasure`,
    `owner to service`,
    `owner to show off a|their feminineness`,
    `dicks to worship`,
    `dicks to prostrate a|themself before`,
    `a|their owner's genitals to worship`,
    `a|their owner's body to worship`,
    `your genitals`,
    `your body`,
  ],
  training_pet_basic: [
    `a|their owner to play fetch with`,
    `a|their owner to sniff`,
    `a|their owner's feet to lick clean`,
    `a|their owner's genitals to lick`,
    `a|their owner's shoes to lick clean`,
    `dog bowl to eat from`,
    `dicks to eat from as a reward`,
    `a|their owner for a walkie`,
    `your feet to lick`,
    `you to play fetch with`,
  ],
  training_pony_basic: [
    `a|their owner to be ridden`,
    `a|their owner to smell`,
    `a|their owner to use a|them as the beast of burden a|they a|is`,
    `a|their owner riding crop to whip a|them with`,
    `a|their owner's carriage to pull`,
    `through to eat from`,
    `a|their owner's attention`,
    `a|their owner's care`,
    `you and your riding crop`,
    `you to ride a|them`,
  ],
  training_dominance_basic: [
    `a submissive slave to dominate`,
    `a|their owner to ask for the next slave to dominate`,
    `fellow slave to dominate`,
    `others to dominate`,
    `weaker minded people to dominate`,
    `a|their owner for permission to dominate others`,
    `other slaves to whip`,
    `other slaves to discipline`,
    `other slaves to train`,
    `you for permission to use your slaves`,
  ],
  training_masochist_basic: [
    `a|their owner's abuse`,
    `being abused`,
    `being tortured by a|their owner`,
    `a|their owner to punish them`,
    `more punishment`,
    `more pain`,
    `punishments from your slavers`,
    `hard whipping`,
    `your abuse`,
    `you to abuse a|them`,
  ],
  training_toilet_basic: [
    `a|their owner's piss`,
    `being used as a toilet`,
    `being used as an urinal`,
    `a|their owner's bodily fluids`,
    `being installed in your toilet`,
    `being pissed on`,
    `your slavers' piss`,
    `being used as a living toilet`,
    `your piss`,
    `you to use a|them as a toilet`,
  ],
  training_endurance_basic: [
    `a|their owner's command`,
    `being used as a chair`,
    `being used as a footstool`,
    `being used as a decoration`,
    `a|their owner to play with a|their body`,
    `a|their owner to play with a|their genitals`,
    `being installed as a statue`,
    `being installed as a living decoration`,
    `being used as your chair`,
    `being molested by you`,
  ],
  training_horny_basic: [
    `a|their owner's instructions`,
    `a|their owner's orders`,
    `being edged`,
    `being allowed to cum`,
    `a|their owner permission to cum`,
    `a|their owner permission to get hard`,
    `a|their genitals to be manhandled`,
    `permission to cum`,
    `your permission to cum`,
    `your next order`,
  ],
  training_roleplay_basic: [
    `fantasies to fulfill`,
    `plays to enact`,
    `a|their owner's darkest desires`,
    `a|their owner's secret desires`,
    `a|their owner's fantasies`,
    `mirror to practice speech`,
    `your deepest secret fantasies`,
  ],
  training_domestic_basic: [
    `rooms to clean`,
    `bathrooms to clean`,
    `floors to swipe`,
    `a|their owner to serve`,
    `your slavers to serve`,
    `dirty rooms to wipe clean`,
    `menial tasks to complete`,
    `a|their owner to give a|them orders`,
    `your orders`,
    `your fort dirtiest places to clean`,
  ],
}
